### ISSUE TITLE
I can't edit this

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#10]
Something is wrong with the permissions. 
When I try and edit (eg. Readme.md on the Dev branch) it either forks the repo to my user and then edits it, or else it creates a new branch or else it says "proposed change" instead of "commit changes" in the button at the bottom.

**Comment by Volxz** [comment]
Should be fixed. Sorry for the delay as I'm doing science expo for 5024 today

**Comment by salamander2** [comment]
no rush. It's fixed. I don't know what happened as I had accepted the invitation already earlier.

**Comment by Volxz** [comment]
Just a quick summary of the changes i made. First off I promoted your account on the organization to administrator then I added you to the repo itself as I think organizations and repos have different permission systems. 

Anyways just a side note, when you are ready to merge into the dev branch just make a pull request on git. any merges into the master branch should be tested and staged before use.
