### ISSUE TITLE
Input box doesnt autofocus

### ISSUE THREAD

**Issue by Volxz** [BealDevelopment/BluePanel#18]
On the kiosk display page (the one where students sign in and out) the box doesn't auto focus after entry. This is a problem because teachers want to use card scanners.

**Comment by salamander2** [comment]
I'll look into it. It may also be browser dependent. I'm sure that we can get it working in Chrome. IE??

**Comment by salamander2** [comment]
Fixed. I needed to change the sweetalert timeout to a function instead of a simple timeout.

**Comment by salamander2** [comment]
@Volxz  BRANCH PROBLEM:  I tried to merge the MH branch into DEV and actually get rid of the MH branch because it's beginning to bug me, but I don't know what happened. It doesn't seem to have worked.  Maybe you can show me your workflow with branches sometime.

**Comment by Volxz** [comment]
@salamander2 its all good. I reviewed changes made and nothing happened except an empty merge. Best to edit on the dev branch and make PR's to the master.
