### ISSUE TITLE
Data tables for all logs search.

### ISSUE THREAD

**Issue by Volxz** [BealDevelopment/BluePanel#20]
Mr. F requested a feature to be able to search for a student at all kiosks. I'm unsure how we can cleanly do this but I know it's possible.

**Comment by salamander2** [comment]
Yep. I want this to. It shouldn't be that hard ...

**Comment by Volxz** [comment]
This will no longer be needed when

**Comment by Volxz** [comment]
When my phone stops glitching out and I can refer to the student search feature!
