### ISSUE TITLE
Unique url session handler

### ISSUE THREAD

**Issue by Volxz** [BealDevelopment/BluePanel#21]
I need to create a url which authenticates a guest user. I will probably use a cookie.

**Comment by salamander2** [comment]
Interesting. Why? And what do we do about teachers viewing the kiosks? (login, etc).  I don't think an obfuscated URL is the way to go.

**Comment by Volxz** [comment]
He wants some form of guard in place over top of the guest interface.its understandable to avoid students who think they are clever by copying the url. I can make a middleware for it in under 5 minutes. I can show you tomorrow.

**Comment by salamander2** [comment]
Bug: The home screen no longer works if you are not logged in. You are always at the Guest screen. EVEN if you have already logged in and then logged off. You can no longer see the list of present students UNLESS you log in.

**Comment by Volxz** [comment]
Have you tried going to the auth url? It works for me.

**Comment by salamander2** [comment]
Oops. No.
