### ISSUE TITLE
Kiosk Logs separated by date

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#25]
It would be nice to have the kioks logs to have a header line in the display when each new date starts. This would make it easier to find a particular date.

I guess we still have to do more with the logs (like what happens after a month).

Oh! Let's add a new option: yesterday's logs, so teachers can just look at yesterday's logs (and include today's too). I think that this will take care of most of what the teachers might look for.

**Comment by salamander2** [comment]
I can't get it to work:

I'm trying various things in app/Http/Controllers/KioskController.php:

`/**                                                                                                                                                                                              
 39      * Show the logs of a kiosk.                                                                                                                                                                     
 40      *                                                                                                                                                                                               
 41      * @param Request $request                                                                                                                                                                       
 42      * @param Kiosk   $kiosk                                                                                                                                                                         
 43      *                                                                                                                                                                                               
 44      * @return Response                                                                                                                                                                              
 45      */                                                                                                                                                                                              
 46     public function logs(Request $request, Kiosk $kiosk)                                                                                                                                             
 47     {                                                                                                                                                                                                
 48         if ($request->ajax()) {                                                                                                                                                                      
 49             return datatables()->of($kiosk->logs)->make(true);                                                                                                                                       
 50             //return datatables()->of($kiosk->logs)->whereDate('created_at', '=', date('2018-01-19'))->make(true);                                                                                   
 51 //select current month                                                                                                                                                                               
 52 //              logs::where('created_at', '>=', Carbon::now()->startOfMonth())->get();                                                                                                               
 53 //select current day                                                                                                                                                                                 
 54 //  whereDate('created_at', '=', \Carbon\Carbon::today()->toDateString())                                                                                                                            
 55         } else {                                                                                                                                                                                     
 56             return view('kiosklogs')->with('kiosk', $kiosk);                                                                                                                                         
 57             //return view('kiosklogs')->with('kiosk', $kiosk)->with('created_at', date('2018-01-19'));                                                                                               
 58             //return view('kiosklogs')->with('kiosk', $kiosk)->whereDate('created_at', '=', date('Y-m-d'));                                                                                          
 59         }                                                                                                                                                                                            
 60     }            `

**Comment by Volxz** [comment]
return datatables()->of($kiosk->logs)->make(true); is the line where things need to be modified. Thats the only line specifically the $kiosk->logs

**Comment by salamander2** [comment]
We need this before semester 2 starts. "This" being an entry for today's logs and an entry for yesterday's logs.

**Comment by salamander2** [comment]
@Volxz Can you get this working soon?

**Comment by salamander2** [comment]
Done! Thanks.
