### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#27]
Hi.
I've just made some minor cosmetic changes (UI), and also pushed the stuff you did on Thursday (timeouts) to the DEV branch. **I'm going to let you do the merging from dev to master.** And also merge master commits back into DEV when they're missing.

I really wish I had a development machine to test more complicated things on. But I haven't had time to learn how to set one up and I have to spend tomorrow marking. 

If I have time on Sunday, I'll work on one of the issues I'm assigned to.

P.S.  Since I do testing on the main server, I've temporarily added code to display the branch that is being used by BluePanel. I'll be working in DEV or a short term branch that I set up, but I want to go back to MASTER for the library to test.

**Comment by salamander2** [comment]
Oh, also, on the kiosk for signing in and out, maybe we could see how it looks if the Beal logo is about 10% smaller. It takes up so much space and is so striking, that it took me a while to figure out where the text is that says which kiosk the computer is logged on to.

**Comment by Volxz** [comment]
I can definitely do code review before merges into master. Just make PR's and I can approve or disprove of them after testing. Its just difficult to know when code is production ready or not. Anyways thats what tests are for and we will set those up later.

For development machine help look here https://laravel.com/docs/5.5/homestead as this makes your life significantly easier by running all the backend stuff in a VM and simply linking the folder from your local machine to the server VM. Its pretty cool and has made my life significantly easier.

**Comment by Volxz** [comment]
This is not related to any current issues so im closing it for now.
