### ISSUE TITLE
IE cannot launch kiosk

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#32]
If the program runs in Internet Explorer, you cannot launch a kiosk.
Weird huh. We found this out because the library computer started IE instead of Chrome.  We're fixing it now.

**Comment by Volxz** [comment]
Considering the deprecation of IE and all of its CSS bugs I dont plan to support it especially with its half baked javascript api. This quick gif here describes the problem very well https://i.exclnetworks.com/g/zTyin

**Comment by salamander2** [comment]
Sweet!
