### ISSUE TITLE
Autostart kiosk

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#33]
We need the kiosk computers to be able to start automatically. 

Right now, it might be possible using the URL if you know the kiosknumber (eg. http://10.10.102.102:8080/kiosks/2  ... 2 being the library). 

BUT, what would be good way of doing it is having a key file on the hard drive somewhere. This file has a hexcode to authenticate that it's a valid machine, and then have a string to say which kiosk it should log into. 

e.g. c:\program data\Beal\autologin.txt
authcode:48309FF753272D44C9AF4245D1EA53
location:library

1. Do we even need an authcode?
2. The location would have to be spelled correctly. It would then look up the kiosk number based on the location name.

**Comment by Volxz** [comment]
My two cents on this would be to have some kind of MySQL authcode stored in a column on the kiosks table. This would allow for us to change the codes as needed. For instance our URL could be http://10.10.102.102:8080/kioskauth/455u4JHRTJT%I^%&drhr6u%$^$ERHDRHDSR etc you get the idea and would create a session cookie for the kiosk associated with that unique key

**Comment by salamander2** [comment]
It seems much more complicated and more liable to break/harder to maintain. I don't see the point, but maybe you can explain it to me (in person).

**Comment by Volxz** [comment]
Check out #35 this will be a good solution
