### ISSUE TITLE
Replace email authentication with username authentication

### ISSUE THREAD

**Issue by salamander2** [BealDevelopment/BluePanel#49]
I'd like this to be done by the end of the week. Student Success wants this go live at the beginning of semester 2.

Rationale: 

1. we're trying to make this really user-friendly. If we don't need something, then we don't need to implement it. 
2. We're not able to send out emails anyway
3. If we ever did have to send out emails, we could always switch back.

I've tried doing this (based on online docs) but it requires a migration (probably deleting and recreating the users table).

**Comment by Volxz** [comment]
Completed in #50
